<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="ClosedXML" />
    <PackageReference Include="CsvHelper" />
    <PackageReference Include="DocumentFormat.OpenXml" />
    <PackageReference Include="PDFsharp" />
    <PackageReference Include="Microsoft.Testing.Extensions.CodeCoverage" />
    <PackageReference Include="xunit.v3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\FluentDocs.Testing\FluentDocs.Testing.csproj" />
  </ItemGroup>

</Project>
